name: "StartupBus"
permalink: pretty

#
# Plugin: jekyll-assets
#
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/js
    - _assets/css
    - _assets/img
  #js_compressor: nil
  #css_compressor: nil
  cachebust: hard
  cache: false
  gzip: [ text/css, application/javascript ]
